name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: self-hosted
    name: Build and run tests

    steps:
      - name: Check out Source
        uses: actions/checkout@v2
        with:
          submodules: "true"
      - name: test
        working-directory: .
        run: swift test
  lint:
    runs-on: self-hosted
    name: Run Swiftlint
    needs: test

    steps:
      - name: Check out Source
        uses: actions/checkout@v2
        with:
          submodules: "true"
      - name: Swiftlint
        run: /opt/homebrew/bin/swiftlint
