name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: swift:5.5-focal

    steps:
    - name: Check out Source
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Build and Run Tests
      working-directory: telemetry
      run: swift test
