name: Test Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: swift:5.9-jammy

    steps:
      - name: Check out Source
        uses: actions/checkout@v2
        with:
          submodules: "true"
      - name: Build for Release
        run: swift build -c release
